services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: agent-service
    ports:
      - "5002:5002"
    volumes:
      - .:/app
    env_file:
      - local.env
    environment:
      - ENVIRONMENT=LOCAL
    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: agent-mongo
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
