version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile.dev
    container_name: user-server
    ports:
      - "5001:5001"
    env_file:
      - local.env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - mongo
    command: npm run start
    restart: unless-stopped

  mongo:
    image: mongo:7
    container_name: mongo-server
    restart: unless-stopped
    ports:
      - "27019:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
